version: 2
updates:
  # npm依存関係の更新設定
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "22:00"
      timezone: "UTC"
    open-pull-requests-limit: 3

  # GitHub Actionsの更新設定
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "22:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
